apiVersion: v1
kind: Service
metadata:
  annotations:
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/name: scrappy-app
    load-balancer.hetzner.cloud/health-check-port: "10254"
    load-balancer.hetzner.cloud/health-check-protocol: "http"
    load-balancer.hetzner.cloud/health-check-http-path: "/healthz"
    load-balancer.hetzner.cloud/protocol: "http"
    load-balancer.hetzner.cloud/use-private-ip: "true"
  creationTimestamp: null
  labels:
    service: app
  name: app
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 80
    targetPort: 8000
  selector:
    run: app
status:
  loadBalancer: {}
