# Generated by Django 3.1.6 on 2021-02-03 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20210128_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrappyuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='scrappyuser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='scrappyuser',
            name='firstname',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrappyuser',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrappyuser',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('PENDING', 'pending'), ('DEACTIVATED', 'deactivated')], default='PENDING', max_length=20),
        ),
    ]
