# Generated by Django 3.1.6 on 2021-02-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_auto_20210203_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappyuser',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scrappyuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
