# Generated by Django 3.1.6 on 2021-02-03 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_auto_20210203_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.CharField(choices=[('ARRIVAL', 'Arrival'), ('PAYOUT', 'Payout'), ('OFFICE', 'Office')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Rights',
                'db_table': 'rights',
            },
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('IDCARD', 'IDCard'), ('PASSPORT', 'Passport'), ('DRIVERLICENSE', 'Driver License')], max_length=20)),
                ('document_id_number', models.CharField(max_length=255)),
                ('name_on_document', models.CharField(max_length=255)),
                ('issuing_country', models.CharField(max_length=255)),
                ('document_expiration_date', models.DateField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identification',
            },
        ),
    ]
