# Generated by Django 3.1.6 on 2021-02-03 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_identification_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='identification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.identification'),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal',
            },
        ),
    ]
