# Generated by Django 3.1.6 on 2021-02-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_auto_20210203_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='document_type',
            field=models.CharField(choices=[('IDCard', 'IDCard'), ('Passport', 'Passport'), ('Driver License', 'Driver License')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rights',
            name='right',
            field=models.CharField(choices=[('Arrival', 'Arrival'), ('Payout', 'Payout'), ('Office', 'Office')], max_length=10),
        ),
        migrations.AlterField(
            model_name='scrappyuser',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Deactivated', 'Deactivated')], default='Pending', max_length=20),
        ),
    ]
