# Generated by Django 3.1.6 on 2021-02-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_custominvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominvitation',
            name='arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custominvitation',
            name='office',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custominvitation',
            name='payout',
            field=models.BooleanField(default=False),
        ),
    ]
