# Generated by Django 3.1.6 on 2021-02-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0014_auto_20210210_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrappyuser',
            name='status',
        ),
        migrations.AddField(
            model_name='scrappyuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
