# Generated by Django 3.1.6 on 2021-02-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0015_auto_20210216_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrappyuser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='scrappyuser',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Deactivated', 'Deactivated')], default='Active', max_length=20),
        ),
    ]
