# Generated by Django 3.1.6 on 2021-02-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0016_auto_20210216_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='document_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
