# Generated by Django 3.1.6 on 2021-02-19 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0017_auto_20210219_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='verified_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
