# Generated by Django 3.1.6 on 2021-02-19 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0019_auto_20210219_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='identification',
        ),
        migrations.AddField(
            model_name='identification',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='office.customer'),
            preserve_default=False,
        ),
    ]
