# Generated by Django 3.1.6 on 2021-04-19 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0020_auto_20210219_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifications', to='office.customer'),
        ),
    ]
