# Generated by Django 3.1.6 on 2021-02-03 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0007_auto_20210203_1558'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arrival', '0002_auto_20210203_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('paid_amount', models.FloatField()),
                ('vat_rate', models.FloatField()),
                ('vat_amount', models.FloatField()),
                ('arrival', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arrival.arrival')),
                ('identification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='office.identification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payout',
            },
        ),
    ]
