# Generated by Django 3.1.6 on 2021-03-01 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0020_auto_20210219_1745'),
        ('payout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='identification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.identification'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='paid_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payout',
            name='vat_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payout',
            name='vat_rate',
            field=models.FloatField(default=0),
        ),
    ]
