# Generated by Django 3.1.6 on 2021-03-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0002_auto_20210203_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Paid', 'Paid')], default='Open', max_length=10),
        ),
    ]
