# Generated by Django 3.1.6 on 2021-03-19 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0003_auto_20210301_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrival',
            name='gross_weight_kg',
        ),
        migrations.RemoveField(
            model_name='arrival',
            name='material',
        ),
        migrations.RemoveField(
            model_name='arrival',
            name='net_weight_kg',
        ),
        migrations.RemoveField(
            model_name='arrival',
            name='tare_kg',
        ),
        migrations.CreateModel(
            name='ArrivalPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_weight_kg', models.FloatField()),
                ('tare_kg', models.FloatField()),
                ('net_weight_kg', models.FloatField()),
                ('arrival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arrival.arrival')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arrival.material')),
            ],
        ),
    ]
