# Generated by Django 3.1.6 on 2021-03-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0004_auto_20210319_1858'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='arrivalpos',
            table='arrival_pos',
        ),
    ]
