# Generated by Django 3.1.6 on 2021-04-19 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0006_auto_20210319_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivalpos',
            name='arrival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_pos', to='arrival.arrival'),
        ),
        migrations.AlterField(
            model_name='arrivalpos',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_pos', to='arrival.material'),
        ),
    ]
